from korapay_client.base_clients import BaseClient


class KorapayClient(BaseClient):
    def charge_via_card(self): ...

    def authorize_card_charge(self): ...

    def resend_card_otp(self): ...

    def charge_via_bank_transfer(self): ...

    def create_virtual_bank_account(self): ...

    def get_virtual_bank_account(self): ...

    def get_virtual_bank_account_transactions(self): ...

    def credit_sandbox_virtual_bank_account(self): ...

    def charge_via_mobile_money(self): ...

    def authorize_mobile_money_charge(self): ...

    def resend_mobile_money_otp(self): ...

    def resend_stk(self): ...

    def authorize_stk(self): ...

    def initiate_charge(self): ...

    def get_charge(self): ...
    def resolve_bank_account(self): ...

    def get_balances(self): ...

    def get_banks(self): ...

    def get_mmo(self): ...

    def payout_to_bank_account(self): ...

    def payout_to_mobile_money(self): ...

    def bulk_payout_to_bank_account(self): ...

    def get_payouts(self): ...

    def get_bulk_transaction(self): ...

    def verify_payout_transaction(self): ...
